### ISSUE TITLE
Pom Tweaks post transfer

### ISSUE THREAD

**Issue by hyandell** [danielgmyers/flux-swf-client#53]
* Change the license url from https://aws.amazon.com/apache2.0 to https://www.apache.org/licenses/LICENSE-2.0
* Change <developers>
* Change <scm> information
* Change <url>

**Comment by danielgmyers** [comment]
Need to update the maven publishing endpoint as per https://issues.sonatype.org/browse/OSSRH-81206 to `https://s01.oss.sonatype.org`.
