### ISSUE TITLE
Set tags on workflow execution start

### ISSUE THREAD

**Issue by joeymarylander** [danielgmyers/flux-swf-client#60]
I would like to be able to query workflows based on a set of tags that I can provide when I start my workflow execution. SWF already supports this (see [here](https://docs.aws.amazon.com/amazonswf/latest/developerguide/swf-dg-tagging.html)). But there is no way to do this today with flux. 

I'd imagine we would need to adjust the [signature](https://github.com/danielgmyers/flux-swf-client/blob/main/flux/src/main/java/software/amazon/aws/clients/swf/flux/FluxCapacitorImpl.java#L188) for `FluxCapacitor.executeWorkflow` to optionally take in a map of tags. 

The main usage I am targeting are based on some sweepers that directly call the `fluxCapacitor.executeWorkflow` method, but I am sure there are other ways you might want to use this. Namely, you might have a set of static tags that you put in your `implements Workflow` class that get assigned each run of the workflow.

**Comment by joeymarylander** [comment]
I guess, actually, it just takes a list of tags, not a set of k/v pairs like most tags. Likely will take a crack at adding this in the next week or so - time permitting.

**Comment by danielgmyers** [comment]
Taking a list of tags as input to `executeWorkflow` makes sense to me. I'm not sure what the use case would be for a static set of tags used for all instances of a given workflow type, since you could infer the same information from the workflow name. Can you give an example of how you'd use those?

**Comment by joeymarylander** [comment]
>Can you give an example of how you'd use those?
The best example I have is if you wanted to list all of your running workflows grouped by some taskList, since there is no way to query that dimension natively via their List*WorkflowExecutions, you could utilize tags to accomplish this.

**Comment by danielgmyers** [comment]
At them moment I'm leaning toward just always including the task list name in the tag list for all workflows, and limiting the list passed to `executeWorkflow` to just 4 tags. I can't think of a good reason to _not_ do that, since we're not tagging workflows at all right now, but just in case, the auto-tagging behavior could be configurable via `FluxCapacitorConfig`.

Would that work for your use case @joeymarylander ?

**Comment by danielgmyers** [comment]
I'll release 2.0.8 with this feature shortly. Remember that 2.0.8 is under a new maven group ID (`com.danielgmyers.flux.clients.swf`), but the Java package names have not changed yet.
